services:
  db:
    container_name: sgta-db
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: sgta
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sgta
    ports:
        - 5435:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    container_name: sgta-api
    build:
      context: .
    environment:
      ADDITIONAL_OPS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sgta
      SPRING_DATASOURCE_USERNAME: sgta
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
        - db
    ports:
        - 8000:8080
        - 5005:5005
    networks:
        - backend

volumes:
    db-data:
networks:
    backend:
      driver: bridge